### ISSUE TITLE
Mismatches between Stated Canton Version Types in Documentation

### ISSUE THREAD

**Issue by benm-da** [digital-asset/daml-platform-observability-example#25]
## Issue

In the Platform Observability documentation, the key references are to Daml Enterprise:

This project demonstrates a [Daml Enterprise](https://www.digitalasset.com/products/daml-enterprise) deployment's observability features, along with example Grafana dashboards.

The prerequisites also refer to Enterprise version software:

Prerequisites
[Docker](https://docs.docker.com/get-docker/)
[Docker Compose plugin 2.x](https://github.com/docker/compose)
Artifactory credentials to access our private [Canton Enterprise Docker images](https://digitalasset.jfrog.io/ui/repos/tree/General/canton-enterprise-docker/digitalasset/canton-enterprise/latest)

Yet the default configuration in the .ENV file is the Open Source version:

```
CANTON_IMAGE=digitalasset/canton-open-source
CANTON_VERSION=2.6.4
SDK_VERSION=2.6.3
LOG_LEVEL=INFO
COMPOSE_FILE=docker-compose-observability.yml:docker-compose-canton.yml:docker-compose-daml-services.yml
```

## Suggestion
Set the default configuration set to Daml/Canton Enterprise but also supply the Openb Source version commented out:

```
CANTON_IMAGE=digitalasset-docker.jfrog.io/digitalasset/canton-enterprise
CANTON_VERSION=2.6.0
SDK_VERSION=2.6.0
LOG_LEVEL=INFO
# CANTON_IMAGE=digitalasset/canton-open-source
# CANTON_VERSION=2.6.3
```

## Errata
This example shows how to switch from the [Daml Enterprise](https://www.digitalasset.com/products/daml-enterprise) Docker images to the open source version (pulled from Docker Hub) set the variables to a similar value below. This example retrieves the v2.5.0 images for the open source repo of Daml.

```
CANTON_IMAGE=digitalasset/canton-open-source
CANTON_VERSION=2.6.0
SDK_VERSION=2.6.0
LOG_LEVEL=INFO
```

**Comment by davidd-da** [comment]
Fixed by https://github.com/digital-asset/daml-platform-observability-example/pull/31
