### ISSUE TITLE
Missing YAML Configuration File (Error 404)

### ISSUE THREAD

**Issue by benm-da** [digital-asset/daml-platform-observability-example#26]
## Issue

In the [Important Endpoints to Explore](https://github.com/digital-asset/daml-platform-observability-example#important-endpoints-to-explore) section, the documentation states that you should check all exposed services/ports in the [Docker compose YAML](https://github.com/digital-asset/daml-platform-observability-example/blob/main/docker-compose.yml) definition.

Hyperlink [Docker Compose YAML](https://github.com/digital-asset/daml-platform-observability-example/blob/main/docker-compose.yml) is Error 404.

## Proof

Please find a screenshot of the missing reference:

<img width="1563" alt="SCR-20230619-msow" src="https://github.com/digital-asset/daml-platform-observability-example/assets/97409833/d05281a0-3fcc-47ad-b50d-a7843060275f">

**Comment by davidd-da** [comment]
Fixed by https://github.com/digital-asset/daml-platform-observability-example/pull/31
