### ISSUE TITLE
The Compose file contains 'true', which is an invalid type, it should be a string, number, or a null

### ISSUE THREAD

**Issue by michael-godfrey-da** [digital-asset/daml-platform-observability-example#29]
When I clone and run:
```bash
daml-platform-observability-example$ sudo docker-compose up
```

I get the following errors:

In file, `docker-compose-observability.yml`

> **ERROR**: The Compose file './docker-compose-observability.yml' is invalid because:
> services.postgres-exporter.environment.PG_EXPORTER_AUTO_DISCOVER_DATABASES contains true, which is an invalid type, it should be a string, number, or a null
> 

In file, `docker-compose-daml-services.yml`

> **ERROR**: The Compose file './docker-compose-daml-services.yml' is invalid because:
> services.trigger-service.environment.LOG_ENCODER_JSON contains true, which is an invalid type, it should be a string, number, or a null

I am able to fix this by changing `true` to `1` in both files

**Comment by davidd-da** [comment]
This is probably because you are using the deprecated "python" Docker compose v1 with `docker-compose`. You need to use Docker compose v2 (complete rewrite as a plugin) with `docker compose`.

More info here https://docs.docker.com/compose/migrate/
